In [8]:
import numpy as np
import time

In [20]:
size=100000
arr_list = list(range(size))
start = time.time()
for i in arr_list:
    i**2
end = time.time()
print(f"time in normal list is {end - start} seconds")


arr2= np.array(arr_list)
start = time.time()
arr2=arr2**2
end = time.time()
print(f"time for numpy calculation is {end-start} seconds")

time in normal list is 0.006127834320068359 seconds
time for numpy calculation is 0.0 seconds


In [25]:
arr = np.array([[1,2,3,5],[2,4,4,5],[2,3,4,5]])
print(arr,type(arr))

[[1 2 3 5]
 [2 4 4 5]
 [2 3 4 5]] <class 'numpy.ndarray'>


In [ ]:
arr1 = np.zeros((2,3),dtype="int64")
arr2 = np.ones((5))
arr3 = np.full((2,3), 99)
arr4 = np.identity((3),4)
print(arr4, type(arr4))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] <class 'numpy.ndarray'>
