In [4]:
import numpy as np
import time

In [5]:
size=100000
arr_list = list(range(size))
start = time.time()
for i in arr_list:
    i**2
end = time.time()
print(f"time in normal list is {end - start} seconds")


arr2= np.array(arr_list)
start = time.time()
arr2=arr2**2
end = time.time()
print(f"time for numpy calculation is {end-start} seconds")

time in normal list is 0.013223648071289062 seconds
time for numpy calculation is 0.0010852813720703125 seconds


In [6]:
arr = np.array([[1,2,3,5],[2,4,4,5],[2,3,4,5]])
print(arr,type(arr))

[[1 2 3 5]
 [2 4 4 5]
 [2 3 4 5]] <class 'numpy.ndarray'>


In [7]:
arr1 = np.zeros((2,3),dtype="int64")
arr2 = np.ones((5))
arr3 = np.full((2,3), 99)
arr4 = np.identity((3))
# range = start, end, step
arr5 = np.arange(1,11,3)
arr6 = np.linspace(1,100,4)
print(arr5, type(arr6),arr6.shape)

[ 1  4  7 10] <class 'numpy.ndarray'> (4,)


In [5]:
# properties of numpy array
arr = np.array([3,4,5,7,7,9])
arr.shape
arr.size
arr.dtype
arr.ndim

float_arr = arr.astype(np.float64)
print(float_arr,type(float_arr))

[3. 4. 5. 7. 7. 9.] <class 'numpy.ndarray'>


In [ ]:
# operations on np arrays

arr = np.array([[11,22],[22,44],[55,77]])
reshape= arr.reshape((2,3))
# flattened = arr.flatten()
# print(flattened, (flattened.shape))
print(reshape)

# indexing
# print(reshape[1][0])
row = [1]
col = [0]
print(reshape[row][col])


# fancyindexing
arr=np.array([1,2,5,7,4,6])
idx = [1,2,3]
print(arr[idx])

# slicing
# in normal python array copy is created but in np array view is crated,
# so if we change subarray in normal array,
# normal array will not affect,
# but in np array original array will change

# arr[start:end:step]
print(arr[1:3])


[[11 22 22]
 [44 55 77]]
[[44 55 77]]
[2 5 7]
[2 5]


In [7]:
# Vectorization and Broadcasting
# vectorization: Doing math on an entire array all at once instead of looping through elements one by one.

marks = np.array([80, 85, 90])
updated_marks = marks + 5
print(updated_marks)

# Broadcasting: How NumPy automatically stretches smaller arrays or
# single numbers so they match the shape of larger arrays during math operations.

scores = np.array([
    [50, 60, 70],
    [55, 65, 75],
    [60, 70, 80]
])
bonus = np.array([2, 5, 10])
final_scores = scores + bonus
print(final_scores)

[85 90 95]
[[52 65 80]
 [57 70 85]
 [62 75 90]]


In [ ]:
# Normalization
# Normalization is the process of scaling numeric features in 
# your dataset to a fixed, standardized range — usually between 0 and 1


arr = np.array([[1,2],
               [3,4]])
mean = np.mean(arr)
std = np.std(arr)
normalized_vector = (arr-mean)/std
print(normalized_vector)
print(mean,std)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5 1.118033988749895
